"""Softplayer credential loader.

The softplayer requires fleet-HMAC credentials (bootstrap v2) to talk to the
CMS. There is no built-in default, no legacy register-then-mint-a-token
fallback: if creds aren't present the process refuses to start.

Credentials live in a plain ``KEY=VALUE`` text file generated by the CMS
imager ("Provision Softplayer" tile). Keys mirror the
``agora-fleet.env`` file baked into Pi images:

* ``AGORA_CMS_URL``        -- websocket URL, e.g. ``wss://cms.example.com/ws/device``
* ``AGORA_FLEET_ID``       -- non-empty fleet identifier
* ``AGORA_FLEET_SECRET_HEX`` -- hex-encoded HMAC secret (>=16 bytes / 32 hex chars)
* ``AGORA_CMS_TRANSPORT``  -- optional, "direct" (default) or "wps"

The loader searches, in order:

1. The explicit ``--credentials-file PATH`` argument, if provided.
   Missing/malformed -> hard error (no fallback to the implicit paths).
2. ``%LOCALAPPDATA%\\agora-softplayer\\softplayer.env``.
3. The directory containing the running executable (``softplayer.env``).
4. The current working directory (``softplayer.env``).

The first existing implicit path wins; if it parses cleanly we use it. If
it exists but is malformed we error out rather than silently skip to a
later location.
"""
from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

DEFAULT_FILENAME = "softplayer.env"

# Min HMAC secret length matching ``secrets.token_bytes(16)`` -- the absolute
# floor; the CMS imager generates 32-byte secrets but we accept 16+ so a
# rotated test fleet with a shorter dev key still works.
_MIN_SECRET_BYTES = 16

_KEY_RE = re.compile(r"^[A-Z_][A-Z0-9_]*$")


class CredentialsError(Exception):
    """Base class for credential-loading errors. Carries an operator-friendly hint."""

    def __init__(self, message: str, *, hint: str | None = None) -> None:
        super().__init__(message)
        self.hint = hint


class MissingCredentialsError(CredentialsError):
    """No credentials file was found in any of the search locations."""


class InvalidCredentialsError(CredentialsError):
    """A credentials file was found but couldn't be parsed or validated."""


@dataclass(frozen=True)
class Credentials:
    """Validated softplayer credentials."""

    cms_url: str
    fleet_id: str
    fleet_secret_hex: str
    cms_transport: str
    source_path: Path


def _exe_dir() -> Path:
    """Directory of the running executable.

    For a PyInstaller-frozen build this is the directory containing the
    ``.exe``. For ``python -m agora_softplayer`` it's the directory of the
    Python interpreter, which is a reasonable fallback but not very useful;
    operators running from source should rely on ``%LOCALAPPDATA%`` or the
    explicit flag instead.
    """
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(sys.argv[0]).resolve().parent if sys.argv and sys.argv[0] else Path.cwd()


def _local_app_data_dir() -> Path | None:
    """``%LOCALAPPDATA%\\agora-softplayer``, or ``None`` if unset (non-Windows)."""
    base = os.environ.get("LOCALAPPDATA")
    if not base:
        return None
    return Path(base) / "agora-softplayer"


def _implicit_search_paths(
    *,
    exe_dir: Path | None,
    local_app_data: Path | None,
    cwd: Path | None,
) -> list[Path]:
    """The implicit (non-flag) credential file search order, with duplicates removed."""
    paths: list[Path] = []
    if local_app_data is not None:
        paths.append(local_app_data / DEFAULT_FILENAME)
    if exe_dir is not None:
        paths.append(exe_dir / DEFAULT_FILENAME)
    if cwd is not None:
        paths.append(cwd / DEFAULT_FILENAME)

    seen: set[Path] = set()
    deduped: list[Path] = []
    for p in paths:
        resolved = p.resolve()
        if resolved in seen:
            continue
        seen.add(resolved)
        deduped.append(p)
    return deduped


def _parse_env_file(path: Path) -> dict[str, str]:
    """Parse a simple ``KEY=VALUE`` env file.

    Rules: ``#`` lines and blank lines ignored; first ``=`` splits key from
    value; surrounding single or double quotes are stripped from the value;
    no shell expansion, no multi-line values, no ``export`` prefix.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise InvalidCredentialsError(
            f"could not read credentials file {path}: {exc}",
            hint="Check the file exists and is readable.",
        ) from exc

    out: dict[str, str] = {}
    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise InvalidCredentialsError(
                f"{path}:{lineno}: expected KEY=VALUE, got {raw!r}",
                hint="Lines must be either blank, # comments, or KEY=VALUE.",
            )
        key, _, value = line.partition("=")
        key = key.strip()
        if not _KEY_RE.match(key):
            raise InvalidCredentialsError(
                f"{path}:{lineno}: invalid key {key!r}",
                hint="Keys must match [A-Z_][A-Z0-9_]*.",
            )
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        out[key] = value
    return out


def _validate(env: dict[str, str], source: Path) -> Credentials:
    """Turn a raw parsed env dict into a validated ``Credentials``."""

    def require(name: str) -> str:
        val = env.get(name, "").strip()
        if not val:
            raise InvalidCredentialsError(
                f"{source}: required key {name} is missing or empty",
                hint=(
                    "Re-download the softplayer.env file from the CMS imager "
                    '("Provision Softplayer" tile) and put it next to the .exe.'
                ),
            )
        return val

    cms_url = require("AGORA_CMS_URL")
    fleet_id = require("AGORA_FLEET_ID")
    fleet_secret_hex = require("AGORA_FLEET_SECRET_HEX")

    try:
        secret_bytes = bytes.fromhex(fleet_secret_hex)
    except ValueError as exc:
        raise InvalidCredentialsError(
            f"{source}: AGORA_FLEET_SECRET_HEX is not valid hex ({exc})",
            hint=(
                "The CMS imager emits a hex-encoded HMAC secret. "
                "Re-download the file rather than hand-editing it."
            ),
        ) from exc
    if len(secret_bytes) < _MIN_SECRET_BYTES:
        raise InvalidCredentialsError(
            (
                f"{source}: AGORA_FLEET_SECRET_HEX is too short "
                f"({len(secret_bytes)} bytes, need at least {_MIN_SECRET_BYTES})"
            ),
            hint="Re-generate the fleet from the CMS and download a fresh file.",
        )

    cms_transport = env.get("AGORA_CMS_TRANSPORT", "").strip() or "direct"
    if cms_transport not in ("direct", "wps"):
        raise InvalidCredentialsError(
            f"{source}: AGORA_CMS_TRANSPORT={cms_transport!r} is not one of direct, wps",
            hint="Leave this key out unless you specifically need WPS.",
        )

    return Credentials(
        cms_url=cms_url,
        fleet_id=fleet_id,
        fleet_secret_hex=fleet_secret_hex,
        cms_transport=cms_transport,
        source_path=source,
    )


def load_credentials(
    explicit_path: Path | None = None,
    *,
    exe_dir: Path | None = None,
    local_app_data: Path | None = None,
    cwd: Path | None = None,
) -> Credentials:
    """Resolve, parse, and validate softplayer credentials.

    Parameters are dependency-injection seams for tests; production callers
    pass only ``explicit_path`` (from the ``--credentials-file`` flag) and
    let the other paths default to real-system locations.
    """
    if explicit_path is not None:
        path = Path(explicit_path)
        if not path.is_file():
            raise MissingCredentialsError(
                f"--credentials-file path does not exist: {path}",
                hint="Either drop the flag or point it at an existing softplayer.env.",
            )
        return _validate(_parse_env_file(path), source=path)

    search = _implicit_search_paths(
        exe_dir=exe_dir if exe_dir is not None else _exe_dir(),
        local_app_data=local_app_data if local_app_data is not None else _local_app_data_dir(),
        cwd=cwd if cwd is not None else Path.cwd(),
    )

    for candidate in search:
        if candidate.is_file():
            return _validate(_parse_env_file(candidate), source=candidate)

    searched = "\n".join(f"  - {p}" for p in search)
    raise MissingCredentialsError(
        "No softplayer.env credentials file found.\n"
        f"Searched (in order):\n{searched}",
        hint=(
            "Open the CMS, go to the Imager tab, click \"Provision Softplayer\", "
            "pick a fleet, and download softplayer.env. Drop it next to the .exe "
            f"or place it at %LOCALAPPDATA%\\agora-softplayer\\{DEFAULT_FILENAME}."
        ),
    )
